#
# Module manifest for module 'PwShPodcasts'
#
# Generated by: spencer
#
# Generated on: 24/04/23
#
# Updated manually on: 24/07/31 
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\PwShPodcasts.psm1'

# Version number of this module.
ModuleVersion = '1.5.0'

# ID used to uniquely identify this module
GUID = '91b7bd0c-89a3-467b-a8b9-2f5a6ae376c8'

# Author of this module
Author = 'Spencer Frisby'

}

